import os

from matplotlib import pyplot as plt

from data import save_plot


# Generated by Abedalrahman Rasem


class TestSavePlot:

    #  Save a plot successfully with a valid plot and file name
    def test_valid_plot_and_file_name(self):
        # Create a valid plot
        plot = plt.figure()
        plt.plot([1, 2, 3, 4], [1, 4, 9, 16])

        # Call the save_plot function with a valid plot and file name
        save_plot(plot, 'valid_plot.png')

        # Assert that the file is saved successfully
        assert os.path.exists('Diagrams/valid_plot.png') is True

    #  Save a plot successfully with a different file name
    def test_different_file_name(self):
        # Create a valid plot
        plot = plt.figure()
        plt.plot([1, 2, 3, 4], [1, 4, 9, 16])

        # Call the save_plot function with a different file name
        save_plot(plot, 'different_file_name.png')

        # Assert that the file is saved successfully
        assert os.path.exists('Diagrams/different_file_name.png') is True

    #  Save a plot successfully with a plot that has no data
    def test_no_data_plot(self):
        # Create a plot with no data
        plot = plt.figure()

        # Call the save_plot function with a plot that has no data
        save_plot(plot, 'no_data_plot.png')

        # Assert that the file is saved successfully
        assert os.path.exists('Diagrams/no_data_plot.png') is True

    #  Save a plot successfully with a plot that has no title
    def test_no_title_plot(self):
        # Create a plot with no title
        plot = plt.figure()
        plt.plot([1, 2, 3, 4], [1, 4, 9, 16])

        # Call the save_plot function with a plot that has no title
        save_plot(plot, 'no_title_plot.png')

        # Assert that the file is saved successfully
        assert os.path.exists('Diagrams/no_title_plot.png') is True

    #  Save a plot successfully with a plot that has no x or y label
    def test_no_labels_plot(self):
        # Create a plot with no x or y label
        plot = plt.figure()
        plt.plot([1, 2, 3, 4], [1, 4, 9, 16])

        # Call the save_plot function with a plot that has no x or y label
        save_plot(plot, 'no_labels_plot.png')

        # Assert that the file is saved successfully
        assert os.path.exists('Diagrams/no_labels_plot.png') is True

    #  Save a plot successfully with a plot that has a long file name
    def test_long_file_name(self):
        # Create a valid plot
        plot = plt.figure()
        plt.plot([1, 2, 3, 4], [1, 4, 9, 16])

        # Call the save_plot function with a long file name
        save_plot(plot, 'this_is_a_very_long_file_name_that_exceeds_the_maximum_allowed_length.png')

        # Assert that the file is saved successfully
        assert os.path.exists('Diagrams/this_is_a_very_long_file_name_that_exceeds_the_maximum_allowed_length.png') is True
