name: Run Python Script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: 3.8  # Change this to the Python version you're using

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate && python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install seaborn 
        pip install matplotlib
        pip install selenium  
        pip install tensorflow
        pip install keras  
        pip install python-docx 
        pip install pyttsx3   
        pip install pandas  

    - name: Run Python script
      run: python main.py  # Replace main.py with the name of your Python script
